services:
  - type: web
    name: fitforge-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd apps/api && npm install && npm run build && npm prune --omit=dev
    startCommand: cd apps/api && node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:uJYwtPIvxGgkjCADbQPbRTBCyyHhENEJ@acela.proxy.rlwy.net:51938/railway
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: NODE_ENV
        value: production
